version: '3.7'

services:
  e_nginx:
    container_name: esustav_nginx
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - 8700:80
    depends_on:
      - e_frontend
      - e_backend
  e_backend:
    build: ./backend
    container_name: esustav_api
    restart: always
  e_frontend:
    container_name: esustav_fe
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
networks:
  default:
