# Generated by Django 4.1.7 on 2023-05-19 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("estudenti", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roles",
            name="role_group_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="estudenti.rolegroups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="estudenti.roles",
            ),
        ),
    ]
