# Generated by Django 4.2.1 on 2023-05-20 20:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("estudenti", "0002_rename_user_userspositions_user_test"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userspositions",
            old_name="user_test",
            new_name="user",
        ),
    ]
