# Generated by Django 4.2.1 on 2023-05-19 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("estudenti", "0003_rename_role_group_id_roles_role_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                ("virtual", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Teams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("short_name", models.CharField(blank=True, max_length=50, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                ("virtual", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "TeamGroups",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="estudenti.teamgroups",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="roles",
            name="role_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="estudenti.rolegroups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="estudenti.roles",
            ),
        ),
        migrations.CreateModel(
            name="UsersPositions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="estudenti.roles",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="estudenti.teams",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
