# Generated by Django 4.2.1 on 2023-05-20 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("estudenti", "0004_teamgroups_teams_alter_roles_role_group_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teams",
            name="virtual",
        ),
        migrations.AlterField(
            model_name="teams",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="VirtualTeams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("short_name", models.CharField(blank=True, max_length=50, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "TeamGroups",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="estudenti.teamgroups",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userspositions",
            name="virtual_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="estudenti.virtualteams",
            ),
        ),
    ]
