# Generated by Django 4.2.1 on 2023-05-20 19:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eizbori", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kandidature",
            old_name="user",
            new_name="candidate_user",
        ),
        migrations.RenameField(
            model_name="votes",
            old_name="user",
            new_name="votes_from",
        ),
    ]
