# Generated by Django 4.1 on 2023-05-25 11:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("estudenti", "0002_remove_user_role_alter_userspositions_virtual_team"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eizbori", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Kandidature",
            new_name="Candidate",
        ),
    ]
