# Generated by Django 4.1 on 2023-05-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eizbori", "0003_rename_kandidature_candidacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="aktivnosti",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
